### ISSUE TITLE
Unexpected token error

### ISSUE THREAD

**Issue by leafarenuk** [0m4r/MMM-euro2024#2]
Hi guys, I got this error:
```
[07.06.2024 21:57.59.661] [ERROR] Whoops! There was an uncaught exception...
[07.06.2024 21:57.59.682] [ERROR] /opt/magic_mirror/modules/MMM-euro2024/node_helper.js:138
      const matches = fixtures?.matches || []
                               ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at loadModule (/opt/magic_mirror/js/app.js:126:19)
    at loadNextModule (/opt/magic_mirror/js/app.js:164:5)
    at /opt/magic_mirror/js/app.js:166:6
[07.06.2024 21:57.59.687] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
```

my config looks like this:
```
{
    disabled: false,
    module: "MMM-euro2024",
    position: "center",
    header: "Euro 2024",
    config: {
    updateInterval: 60 * 1000,
    token: "b1e67..myToken..67c8c5",
    }
},
```

**Comment by 0m4r** [comment]
hi @leafarenuk can you please confirm your node version?
are you on the last version of this module?

I am not able to replicate this error...

**Comment by 0m4r** [comment]
closing as per no feedback provided.
